---
title: "Visualization Concept — Fit / Performance Enhancement Part 2.0: Medical Screening & Monitoring"
draft: true
tags:
date: 2026-06-07
---
# Visualization Concept — Fit / Performance Enhancement Part 2.0: Medical Screening & Monitoring

- **Article:** C:\Users\Nadeem\Desktop\Obsidian\personal-blog\content\2. Panduan Ringkas\If You're So Smart, Why Are You Not\Fit\Performance Enhancement\Part 2.0 - Medical Screening and Monitoring.md
- **Date:** 2026-06-07
- **Series:** If You're So Smart, Why Are You Not → **Fit** pillar → **Performance Enhancement** track (article 2 of 15)
- **Series style lock:** Engineering Diagnostic Instrument (see §6 — locked for the whole Fit pillar)
- **Pairs with:** `aether-call-to-action-DESIGN.md` (in this folder) for all color / type / spacing / surface decisions. This brief sets what the design system should *express*, not the tokens.
- **To produce the poster:** paste this file + `aether-call-to-action-DESIGN.md` into Claude Design (Canva) and ask it to follow both.
- **Arc note:** PE 1.0 was the **commissioning authorization console** — the sign-off gate. This poster is what happens immediately after an honest sign-off and *before first power-up*: the **calibration pass**. Key K4 on the 1.0 panel read `BASELINE MEASURED & CLEAN → Part 2.0` — this poster IS that key, expanded into its own instrument.
- ⚠ **Source-file note for Nadeem:** the article's very last block (the closing `[!danger] Disclaimer` callout) is clipped mid-sentence ("…reference ranges, assay types, and clinical si"). Unlike 1.0's truncation this one costs nothing — the entire body through "Up next" is complete and is what this brief draws on — but the tail should still be repaired before publishing.

---

## Series context & the key point _(why this concept, not a generic one)_

Part 2.0 is the **baseline** article. The whole series rests on Part 1.0's framing (enhancement = a managed trade, spending Healthy to buy Fit), and this article supplies the precondition for "managed": ==you cannot manage what you have never measured.== Its central epistemic move is subtle and very visual: **reference ranges are population averages — the only ranges that matter are the ones *you* personally sit at when healthy.** A baseline is a *photograph of your normal*, taken before you start changing things. In instrument terms: before you energize the system, you **zero every gauge to yourself**, because from now on every reading will be interpreted against that zero, not against the factory-printed band.

Load-bearing ideas the poster must carry:

1. **The zeroing principle (hero).** A baseline does three jobs: (a) **catches dealbreakers** (some people learn from the baseline that they should not do this at all — the screen can output NO-GO, which connects straight back to 1.0's exit rail), (b) **sets your personal reference point** ("is this estradiol high?" is only answerable against *your* healthy number), (c) **captures fertility before you suppress it** (the one measurement you cannot go back and take later). Vigorous Steve's frame: knowing *what to pay attention to* is what determines the success of the first cycle and every cycle after.
2. **Garbage in, garbage out — the prep chain.** Bad prep produces bad data, and bad data drives bad *interventions* (the article's named failure: cranking an aromatase inhibitor against an estradiol number that was never real). Five sample-handling rules: hydrate 1–1.5 L (dehydration fakes high hematocrit/creatinine/electrolytes), fast 10–12 h, draw 07:00–10:00 (hormone circadian peak = comparable numbers), hold hard training 48–72 h (training inflates CPK/AST/ALT), abstain 3 days before the semen analysis.
3. **The lifter's interference problem (the article's smartest teach).** A muscular body *jams the standard sensors*: creatinine-based eGFR makes a big lifter look renally "impaired"; AST/ALT are released by skeletal muscle, so a healthy liver looks stressed. The fix is a **compensated sensor pair**: **cystatin-C** (muscle-mass-independent kidney marker) and **GGT** (liver-specific — if GGT is normal while AST/ALT are high, the elevation is muscular, not hepatic). This is a precise, ownable diagram: raw sensor + known interference source + corrected channel.
4. **The panel as racks, with headline markers.** Six bays, each with one marker that carries the bay: CBC → **hematocrit** (androgens drive RBC production; past ~52–54% = phlebotomy + hydration territory); cardiovascular core → **HDL/ApoB** ("where the real cost shows up first" — orals crush HDL; ApoB is the particle count worth paying extra for); kidney → **cystatin-C**; liver → **GGT**; **the full hormone panel = the most important bay** (it's the system you're about to manipulate: SHBG >~20 nmol/L, sensitive-assay E2, LH/FSH = the signals the cycle will suppress, prolactin = the 19-nor tell, IGF-1 = the GH readout); thyroid/nutrients/electrolytes/heavy metals = the supporting bay.
5. **The growth-signal interlock.** GH, IGF-1, and growth peptides **don't cause cancer — they accelerate whatever is already there.** So before any growth signal enters the protocol: sweep the cancer markers (organ-mapped), every ~3 years, yearly with family history. Plus the pituitary caveat (very high baseline GH/LH/FSH/prolactin before starting anything → investigate first).
6. **The archival copy.** Semen analysis = the fertility "before" picture; if normal, freeze — multiple samples, **more than one clinic**. In engineering terms: write a verified backup of the system state before flashing new firmware, and store it off-site.
7. **The inspection timetable.** Monitoring is continuous, in two layers: home instruments always-on (BP several times/week — "the cheapest early-warning system you have", RHR daily, weight trend) + four blood checkpoints (baseline → mid-cycle wk 4–6 → end/pre-PCT → post-PCT 4–8 wk). The article's sharpest line: ==bloodwork only every 6–12 months is monitoring in name only== — mid-cycle bloods are where disasters (hematocrit at stroke territory, HDL near zero, 150/95 sitting quietly) get caught *while you can still act*.
8. **Malaysia rail.** No sympathetic doctor needed: BP Healthcare / Gribbles / Pathlab / Qualitas walk-ins, ~RM150–400 for the combined core; hospital executive screenings (Sunway, Columbia Asia, Pantai, Gleneagles); InBody RM20–50 / DEXA RM200–400 per the Part 1.1 tiers; home BP cuff RM100–250 = highest-value purchase. Standing-order tip: keep the marker list in the lab's own naming → 30-second reorder.

Prior Fit sub-archetypes already used (must differ from all): lookup matrices (A&S 1.1/1.2), day-strip signal trace (2.0), operating-band curve dashboard (3.1), build-up assembly + standing-orders rail (3.2), dual-config datasheet + timing diagrams (3.3), margin panel + gated two-tier catalog (4.0), cutaway powertrain (Ath 1.0), capacity column (Ath 2.0), oscilloscope bench + safety interlock (Ath 3.1), articulation bench (Ath 3.2), dual-trace interference scope (Ath 4.0), master instrument cluster + annual dial (Ath 5.0), commissioning authorization console (PE 1.0). The clean new fit for *a baseline-before-modification article*: a **pre-energization CALIBRATION BENCH / zeroing station** — the metrology pass every instrument gets before a system is powered for the first time. Three instruments no prior poster used: a **zeroing gauge** (factory band ghosted vs a personally-set zero mark), **compensated sensor pairs** (raw channel + interference source + corrected channel), and a **sealed archival-sample vault chip**.

**The single key point to make a reader feel:** *the lab's printed reference range is a population average — calibration means setting YOUR zero while you're still healthy, because every number you'll ever pull on cycle is only meaningful as a delta from that zero. And a baseline is the one instrument reading with an expiry: take it before pin one or never have it at all.*

---

## 1. The Big Idea

_This is the **Calibration Bench** poster. The hero is a **zeroing gauge**: one instrument face with the factory reference band ghosted (`POPULATION AVERAGE — NOT YOU`) and a freshly-struck personal zero mark (`YOUR ZERO — set while healthy`), stamped with the article's law: `YOU CANNOT MANAGE WHAT YOU HAVE NEVER MEASURED.` Around it, the full calibration pass: a five-step **sample-prep chain** (bad prep → false readings → wrong interventions, with the cranked-AI-against-fake-E2 fault as the worked example), a six-bay **instrument rack** of the baseline panel with each bay's headline marker called out and the hormone bay flagged as the most important, the **compensated sensor pairs** that solve the lifter's interference problem (creatinine→cystatin-C, AST/ALT→GGT), a **growth-signal interlock** (sweep cancer markers before GH/IGF-1 — growth signals grow whatever is already there), a **sealed archival sample** (semen analysis + freeze at >1 clinic — the one reading you can't take later), and an **inspection timetable** (home layer always-on + four blood checkpoints) stamped `EVERY 6–12 MONTHS = MONITORING IN NAME ONLY.` A Malaysia spec rail prices the whole pass in RM._ The poster is the metrology certificate the rest of the 15-article track assumes exists.

## 2. Visual Metaphor & Structure

A **pre-energization calibration bench** — the metrology station where every gauge gets zeroed to the specific machine before first power-up. Visual language: calibration certificates, zero-adjust screws, compensated sensor schematics, sample chain-of-custody tags, inspection timetables. Six functional zones plus a side rail:

- **Zone 1 — The Zeroing Gauge (hero).** One large instrument face. The factory reference band is printed but **ghosted/de-emphasized**, labeled `LAB REFERENCE RANGE — population average`. A bold, freshly-struck zero mark sits at the needle, labeled `YOUR ZERO — your healthy set-point`. A small zero-adjust screw is drawn being turned. Law plate under the face: `YOU CANNOT MANAGE WHAT YOU HAVE NEVER MEASURED.` Three output chips hang off the gauge (what a baseline buys): `① CATCHES DEALBREAKERS — some baselines say: don't.` (with a thin tie-line back to the 1.0 NO-GO rail) · `② YOUR REFERENCE POINT — "is this high?" only answers against you` · `③ FERTILITY, CAPTURED — the reading you can't take later`.
- **Zone 2 — The Sample-Prep Chain (chain-of-custody strip).** Five tagged steps drawn as a specimen-handling sequence: `HYDRATE 1–1.5 L` (dehydration fakes hematocrit · creatinine · electrolytes) → `FAST 10–12 h` → `DRAW 07:00–10:00` (hormones at circadian peak = comparable numbers) → `HOLD TRAINING 48–72 h` (training inflates CPK · AST · ALT) → `ABSTAIN 3 d` (semen analysis). At the strip's end, the fault chip that justifies it: `FALSE E2 READING → AI CRANKED AGAINST A NUMBER THAT WAS NEVER REAL. Bad prep doesn't just lie — it prescribes.`
- **Zone 3 — The Instrument Rack (the baseline panel, six bays).** A rack elevation, each bay a slim module with its headline marker enlarged and one teach-line: `BAY 1 · CBC — headline: HEMATOCRIT` (androgens stimulate RBC production; respect plate: `>52–54% → phlebotomy + hydration → Part 4.0`) · `BAY 2 · CARDIOVASCULAR CORE — headline: HDL + ApoB` (`where the cost shows first` — orals crush HDL; ApoB = particle count, the one extra worth buying; hs-CRP · homocysteine in small print) · `BAY 3 · KIDNEY — headline: CYSTATIN-C` · `BAY 4 · LIVER — headline: GGT` · `BAY 5 · HORMONES — THE MOST IMPORTANT BAY` (drawn slightly wider/brighter: `T total/free · SHBG >~20 nmol/L · E2 sensitive assay · LH/FSH — what the cycle suppresses · prolactin — the 19-nor tell · IGF-1 — the GH readout`; caption `your "after" is meaningless without a complete "before"`) · `BAY 6 · SUPPORT — thyroid · vit D/B12/zinc · electrolytes · heavy metals`.
- **Zone 3b — The Compensated Sensor Pairs (detail inset on the rack).** The lifter's interference problem as a two-channel schematic, drawn once and clearly: interference source `MUSCLE MASS + TRAINING` injects into the raw channels `CREATININE/eGFR` and `AST/ALT` (both flagged `READS FALSELY STRESSED IN LIFTERS`), each paired with its corrected channel `CYSTATIN-C — muscle-independent` and `GGT — liver-specific` with the decoder line `GGT normal + AST/ALT high = muscle, not liver.` Caption: `A LIFTER'S BODY JAMS THE STANDARD SENSORS — ORDER THE COMPENSATED PAIR.`
- **Zone 4 — The Growth-Signal Interlock.** A gate drawn across the input line labeled `GH · IGF-1 · GROWTH PEPTIDES`, held open only by a completed sweep: `CANCER-MARKER SWEEP REQUIRED FIRST.` The physics plate: `GROWTH SIGNALS DON'T CAUSE CANCER — THEY ACCELERATE WHAT'S ALREADY THERE.` A compact organ-map strip (prostate · liver · colorectal · pancreas · lung · stomach · testes · pituitary · thyroid ← AFP · PSA/f-PSA · CEA · CA 19-9 · β-HCG · NSE · hGH …) rendered as a small grid, not a table dump. Cadence chips: `EVERY ~3 YEARS` · `YEARLY if family history`. Pituitary caveat in fine print: `baseline GH/LH/FSH/prolactin very high before starting anything → investigate (imaging) first.`
- **Zone 5 — The Archival Sample (vault chip).** A small sealed-vault module: `SEMEN ANALYSIS — volume · count · concentration · motility · morphology` → `IF NORMAL: FREEZE. Multiple samples · MORE THAN ONE CLINIC.` Teach-line: `a verified backup of the system state, stored off-site, before you flash anything.` Tagged `NON-RETAKEABLE` — the only reading on the bench with an expiry.
- **Zone 6 — The Inspection Timetable (monitoring cadence).** Two layers drawn as a maintenance schedule. **Layer 1 · HOME, ALWAYS-ON:** `BP — several×/week, seated, same hour — the cheapest early-warning system you own` · `RHR — daily trend` · `WEIGHT — trend + water` (pointer chip: `the continuous film → Part 2.1`). **Layer 2 · BLOOD CHECKPOINTS:** four ticks on a cycle-time axis — `BASELINE (full panel)` → `MID-CYCLE wk 4–6 (hematocrit · lipids · E2 · prolactin if 19-nors · liver if orals · glucose if GH)` → `END / PRE-PCT (+ LH · FSH · T)` → `POST-PCT 4–8 wk (did the axis come back?)`. The mid-cycle tick is the emphasized one, with the danger plate: `INVISIBLE WITHOUT MID-CYCLE LABS: hematocrit at stroke territory · HDL near zero · 150/95 sitting quietly.` Stamp across the layer: `EVERY 6–12 MONTHS = MONITORING IN NAME ONLY.`
- **The Malaysia rail (persistent side rail).** Priced like a parts list: `walk-in labs — BP Healthcare · Gribbles · Pathlab · Qualitas — core panel ~RM150–400` · `hospital executive screening — Sunway · Columbia Asia · Pantai · Gleneagles (hormones + markers = add-ons)` · `InBody RM20–50 · DEXA RM200–400 (Part 1.1 tiers)` · `HOME BP CUFF RM100–250 — highest-value purchase on this poster` · `standing order: keep the marker list in the lab's own naming → 30-second reorder · track trends in your spreadsheet`.

Deliberately distinct from every prior Fit sub-archetype: no prior poster zeroed a gauge against a ghosted factory band, drew interference-compensated sensor pairs, or used an archival-vault chip. Where 1.0 (PE) was *the gate examined*, 2.0 is *the metrology pass behind it* — the console authorized power-up; this bench makes the instruments trustworthy before anyone touches the throttle.

## 3. Layout — exact composition

Orientation: **portrait / tall** (a calibration certificate reads top-to-bottom as a procedure). Density: high but procedural — every zone is a step in one pass, numbered like a checklist actually being executed. The Malaysia rail holds a calm right-hand margin the full height.

Zones, top to bottom:

1. **Kicker (top-left):** mono tag — `FIT · PERFORMANCE ENHANCEMENT · PART 2.0 — MEDICAL SCREENING & MONITORING` — right-aligned arc tag: `TIER 3 · article 2 of 15 · = KEY K4 FROM THE PART 1.0 CONSOLE`.
2. **Headline block:** headline (§4), subhead in muted secondary.
3. **Zone 1 · The Zeroing Gauge (hero band, ~20% height):** big face, ghosted population band vs struck personal zero, zero-adjust screw, law plate, three output chips (dealbreakers / reference / fertility).
4. **Zone 2 · The Sample-Prep Chain (~10%):** five chain-of-custody tags left→right ending in the false-E2 fault chip.
5. **Zone 3 · The Instrument Rack (~24%):** six bays stacked; Bay 5 (hormones) wider and brighter; the compensated-pair inset (3b) docked to bays 3–4.
6. **Zone 4 · The Growth-Signal Interlock (~12%):** the gated input line, physics plate, organ-map grid, cadence chips.
7. **Zone 5 · The Archival Sample (~8%):** the sealed vault chip with `NON-RETAKEABLE` tag.
8. **Zone 6 · The Inspection Timetable (~16%):** home layer + four-checkpoint axis, mid-cycle emphasized, the two stamps.
9. **Footer:** arc line (`Gauges zeroed, archive sealed, timetable set? Part 2.1 adds the continuous film; Part 3.0 finally opens the toolbox.`), disclaimer, source line, series mark (`Fit — Performance Enhancement`).

**Eye path:** kicker → headline → **the zeroing gauge lands first** (population band is not you; set your zero while healthy) → the prep chain (or the zero is fake) → the rack (what gets measured, and which marker carries each bay) → the compensated pairs (the lifter-specific trap) → the interlock (no growth signals before the sweep) → the vault (the reading with an expiry) → the timetable (this never ends; mid-cycle is where you save yourself) → footer. The two things a screenshot must carry: the zeroing gauge (your zero vs the population band) and the mid-cycle stamp (`every 6–12 months = monitoring in name only`).

## 4. Copy — exact words _(every label must teach, not decorate)_

**Headline:** `You cannot manage what you have never measured.`
**Subhead:** `Before pin one: zero every gauge to yourself. Lab ranges are population averages — your baseline is the only "normal" that means anything. Prep the sample or the numbers lie. Order the lifter-proof markers. Sweep for what growth signals would feed. Seal the one sample you can never take again. Then monitor like it matters — because bloodwork twice a year is monitoring in name only.`

**Zone 1:** `LAB REFERENCE RANGE — population average · NOT YOU` · `YOUR ZERO — set while healthy` · law plate: `YOU CANNOT MANAGE WHAT YOU HAVE NEVER MEASURED.` · chips: `① CATCHES DEALBREAKERS — some baselines say: don't.` / `② YOUR REFERENCE POINT — "is this high?" only answers against you` / `③ FERTILITY, CAPTURED — before you suppress it`
**Zone 2 tags:** `HYDRATE 1–1.5 L` · `FAST 10–12 h` · `DRAW 07:00–10:00` · `HOLD TRAINING 48–72 h` · `ABSTAIN 3 d` · fault chip: `false E2 → AI cranked against a number that was never real. Bad prep doesn't just lie — it prescribes.`
**Zone 3 bay heads:** `CBC — HEMATOCRIT` (`>52–54% → phlebotomy + hydration → Part 4.0`) · `CARDIO CORE — HDL · ApoB` (`where the cost shows first`) · `KIDNEY — CYSTATIN-C` · `LIVER — GGT` · `HORMONES — THE BAY THAT MATTERS MOST` (`your "after" is meaningless without a complete "before"`) · `SUPPORT — thyroid · nutrients · electrolytes · metals`
**Zone 3b caption:** `A LIFTER'S BODY JAMS THE STANDARD SENSORS — ORDER THE COMPENSATED PAIR.` · decoder: `GGT normal + AST/ALT high = muscle, not liver.`
**Zone 4 plates:** `GROWTH SIGNALS DON'T CAUSE CANCER — THEY ACCELERATE WHAT'S ALREADY THERE.` · `SWEEP BEFORE GH / IGF-1.` · `EVERY ~3 YEARS · YEARLY IF FAMILY HISTORY`
**Zone 5:** `NON-RETAKEABLE` · `IF NORMAL: FREEZE — multiple samples, more than one clinic.`
**Zone 6 stamps:** `EVERY 6–12 MONTHS = MONITORING IN NAME ONLY.` · danger plate: `INVISIBLE WITHOUT MID-CYCLE LABS: hematocrit at stroke territory · HDL near zero · 150/95 sitting quietly.`
**Malaysia rail header:** `DOING THIS IN MALAYSIA — priced like a parts list.`
**Footer arc line:** `Gauges zeroed, archive sealed, timetable set? Part 2.1 adds the continuous film. Part 3.0 opens the toolbox.`
**Disclaimer:** `Harm reduction, not encouragement. Lab interpretation belongs with a physician — ideally one who knows what you're running.`
**Sources:** `Screening framework & panel: Vigorous Steve, "Medical Screening Required Before Your First Cycle" · Cystatin-C / GGT muscle-interference corrections: clinical chemistry literature · Hematocrit & phlebotomy thresholds: AAS harm-reduction literature · MY lab pricing: BP Healthcare / Gribbles / Pathlab / hospital screening packages, 2026.`
**Series mark:** `Fit — Performance Enhancement`

> Copywriting rule for this poster: a stranger who screenshots only the zeroing gauge + the mid-cycle stamp must walk away with the two non-obvious lessons — *the printed lab range is not your range (set your zero while healthy, before you change anything), and monitoring that isn't mid-cycle isn't monitoring.* A second screenshot of the compensated-pair inset should save a real lifter a real false alarm. No compound names beyond the pathway classes the article itself names (GH/IGF-1 as gated inputs); zero drugs are recommended on this poster.

## 5. UX / visual encoding expectations _(semantic — colors come from design.md, not from here)_

- **The ghosting carries the thesis.** The population band must be visibly *printed-on-the-dial* (factory artifact) while the personal zero is *struck/etched* (an act the owner performs). If both render at equal weight the hero collapses into a generic gauge. De-emphasis of the lab range IS the argument.
- **The rack compresses, never dumps.** The article contains five full marker tables; the poster must NOT reproduce them. One headline marker per bay, enlarged, plus a fine-print supporting row. The reader should leave knowing *which six numbers carry the screen*, not facing a wall of assays.
- **The compensated pairs are a schematic, not a footnote.** Draw the interference injection (muscle → raw channel) and the clean corrected channel as actual signal paths. This is the poster's most practically valuable 10 cm² for the target reader.
- **Mid-cycle is the loudest tick.** On the checkpoint axis, baseline/end/post-PCT render as standard ticks; mid-cycle gets the emphasis treatment and owns the danger plate. The cadence law stamps across the whole layer, angled like an inspection stamp.
- **The vault chip must feel terminal.** `NON-RETAKEABLE` is the only expiry tag on the poster — give it the quiet finality of 1.0's one-way door (they're cousins: both are irreversibility devices), but smaller and calmer; it's an instruction, not a warning.
- **Semantic color, rationed:**
  - **Success / go** role — the struck personal zero mark, the completed prep-chain tags, the corrected channels (cystatin-C, GGT), the `IF NORMAL: FREEZE` action.
  - **Warning** role — the hematocrit respect plate (52–54%), the raw jammed channels (creatinine, AST/ALT) and their `READS FALSELY STRESSED` flags, the false-E2 fault chip, the `NON-RETAKEABLE` tag.
  - **Danger** role — exactly TWO objects: the growth-signal physics plate (`accelerate what's already there`) and the mid-cycle invisible-disasters plate. Do NOT red-code the whole rack, the interlock gate itself (the gate is neutral procedure; the *reason* for it is the danger), or the Malaysia rail.
- **Hierarchy of attention:** headline → zeroing gauge → prep chain → rack (Bay 5 brightest) → compensated pairs → interlock → vault → timetable → footer; the Malaysia rail is peripheral but always findable.
- **Saveability:** this is the poster a reader takes *to the lab counter*. The bay headlines + prep chain + checkpoint axis must survive grayscale and a phone screenshot; a reader should be able to order the right panel and book the right follow-ups from the image alone.

## 6. Style Reference — **LOCKED for the entire Fit series**

**Fit pillar style: "Engineering Diagnostic Instrument."** Every poster in the Fit series (Aesthetic & Strength, Athletic, Performance Enhancement) uses this same visual language so the pillar reads as one body of work:

- Schematic, technical, measured — fault charts, gauges, operating-band curves, matrices, signal traces, lookup tables, dashboards, assembly schematics, datasheets, timing diagrams, gated catalogs, hardware interlocks, commissioning consoles, **zeroing gauges, calibration certificates, compensated sensor schematics, chain-of-custody tags, inspection timetables, archival vault chips.** The lifter's body framed as a *system you instrument, read, configure — and, here, calibrate before first power-up.* (This poster's sub-archetype within that language: a **pre-energization calibration bench / zeroing station** — the metrology pass that makes every later reading meaningful.)
- Mono technical labels and tick-marks (design.md's JetBrains Mono role), display face reserved for headline + key terms (design.md's Inter display).
- Status-indicator color logic (semantic states), ruler-drawn lines, generous negative space, dark console ground (all via design.md).
- Reference points: metrology calibration certificates, zero/span adjustment procedures, sensor datasheets with interference-compensation notes, aircraft pre-flight inspection cards, *Information is Beautiful* clarity with an engineering accent.

**Policy:** do not change style mid-pillar. Performance Enhancement is a track inside the Fit pillar, so the style carries over unchanged (precedent: Athletic, 2026-06-01; PE 1.0, 2026-06-07). Logged in `Series Style Policy — If You're So Smart, Why Are You Not.md`.

## 7. What to Avoid

1. **Blood-draw clipart.** No syringes, vials, test tubes, blood drops, or a phlebotomist's arm. The article is about *information*, not fluid; the engineering register renders measurements as instruments, never as specimens. (Drug iconography stays banned per the 1.0 precedent — and this article recommends zero compounds anyway.)
2. **The marker mega-table.** The lazy default is reproducing the article's panel tables as one giant grid — accurate, unreadable, unsaveable. The poster's job is the *logic* of the screen (zero yourself, six bays, one headline each, two compensated pairs), not its census.
3. **Red-alert medicalism.** ECG traces flatlining, heartbeat monitors, hospital iconography, an ominous "your results" folder. The article's register is preventive and calm — the only two red objects are the tumor-acceleration plate and the invisible-disasters plate; everything else is procedure, priced in ringgit.
4. **The generic annual-checkup framing.** This must not read like an insurance company's wellness-screening pamphlet (smiling doctor, ticked clipboard). The differentiator is the *personal-zero epistemology* and the *lifter-specific sensor corrections* — keep those as the heroes and the pamphlet cliché can't form.
