---
date: 2026-06-11
pillar: Fit
track: Performance Enhancement
part: "4.1"
title: When the Numbers Move
---

# Blog Viz Poster — 2026-06-11

- **Date:** 2026-06-11
- **Source brief:** `concepts/Visualization Concept — Fit - Part 4.1 (Performance Enhancement) - When the Numbers Move.md` (in the blog folder; today's run, modified 2026-06-11 00:39, cross-checked against the concepts list as the most recent brief)
- **Article:** Fit pillar → Performance Enhancement track → **Part 4.1 — When the Numbers Move** (2nd of the "Protection & the toolbox" sub-arc: 4.0 Protection → **4.1** → 4.2 Ancillaries → 4.3 Bodybuilding Realm → 4.4 Electrolytes → 4.5 Coming Off & PCT)
- **Style:** Fit "Engineering Diagnostic Instrument" (locked) · sub-archetype = **FAULT-RESPONSE LADDER RACK** (new within the PE set, the natural sequel to 4.0's damage-control board)

## Visual concept used

A landscape fault-response ladder rack that draws the article's actual structure rather than a generic wall of organ icons. The load-bearing argument is **one repeated 5-rung ladder glyph** (CONFIRM → CAUSE → PROTOCOL → SUPER-ANCILLARY → PULL-BACK) drawn large as a docked **TEMPLATE LADDER legend** on the left, then echoed in miniature inside every one of the sixteen marker cards, so "a decision tree, not a panic button" is learned once and read everywhere. The descent direction encodes the PE set's drugs-last spine (confirm/cause sit above protocol/ancillary; the Rx is rung 4, flagged with a physician GATE stamp; each card carries a "stops @ rung N" marker showing most settle by rung 2–3). The **CARDIOVASCULAR bay is the dominant compartment** (green-bordered hero, several times the area of the others) with its six markers **cross-linked** by green convergence arrows and a "fix upstream, several settle" law plate — the direct callback to 4.0's converging rupture loop. The two emergencies (a flagged ECG/arrhythmia and a confirmed BP > 180/120) are the **only two reds**: red hatched tabs in a dashed emergency lane that **skip the rack** down a red chute straight to a `CARDIOLOGIST / ER — NOW` box outside the board. Three supporting bays (METABOLIC, HORMONAL with a ⇅ bidirectional flag on E2/SHBG, ORGAN) obey the same ladder grammar in compact rows. Every bay drains down convergence pipes into a single full-width **PULL-BACK SUMP / META-RULE BUS** reading **"THE NUMBER IS THE BOSS — blood work is the final arbiter,"** with a "pre-decide your pull-back values" rivet stamp. Palette held to the locked three-state PE semantics: green = in-range / free levers / the sump, amber = judgement-calls and the pull-back trigger, blue = confirm/measure, neutral instrument ink for protocol, and red rationed to exactly the two ER chutes.

Headline (verbatim from §4): **"When the number moves."** Thesis chip: the five rungs in order. §7 respected — not a re-skin of 4.0, drug never the prominent/first move, red limited to the two emergencies, CV bay biggest and cross-linked (not isolated parallel ladders), no doses on named anabolics, every escalation drug flagged physician-territory, both emergencies flagged as care-not-troubleshooting.

## Outputs

- **PNG:** `visualization/Poster — Fit - Part 4.1 (Performance Enhancement) - When the Numbers Move.png`
- **SVG (raw, editable source):** `visualization/Poster — Fit - Part 4.1 (Performance Enhancement) - When the Numbers Move.svg`
- No prior poster existed for this concept → no deletes needed (one PNG + one SVG).

## Renderer & verification

- **Pipeline:** hand-coded SVG generated by a Python script (`gen_poster.py`, repeated ladder glyphs parametrized) → CairoSVG @2× (Playwright/rsvg unavailable in sandbox, consistent with prior PE runs).
- **Dimensions:** viewBox 1920×1400 (landscape, per brief §3) → PNG 3840×2800, ~782 KB. Verified non-empty, correct dimensions, XML well-formed.
- **Visual QA:** read back full view + region crops (template ladder, CV cards, supporting bays, thesis chip). Caught and fixed in iteration: (1) double-escaped HTML entities in marker names showing literal `&#…;` — switched all data to literal Unicode arrows with consistent escaping; (2) cross-link label overlapping the law plate — moved the tie-strip into the gap below it; (3) CV drain pipe crossing the metabolic bay — rerouted down the clear gutter; (4) template title / grace-gauge / GATE-glyph clipping — shortened/redrawn; (5) thesis-chip sequence collapsing under cairosvg's `text-anchor="end"` + multi-tspan quirk — switched to left-anchored.
- **Note:** the generator file truncated mid-line once during editing (the known sandbox em-dash/long-line truncation); repaired the footer + write tail and re-validated before final render.

## Deviations from the brief

- Brief's primary orientation is landscape; built landscape (1920×1400) as specified. No content deviations — all §4 copy used (headline, subhead, thesis chip, template rungs, CV law plate, the two emergencies, all sixteen marker ladders condensed to fit, sump meta-rule, bidirectional grace-note, footer bridge).
